### ISSUE TITLE
Add support for multiple speakers for a presentation

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/meetups#39]
We have a meetup in Aarhus with multiple speakers, I would expect something like this to work:

```
    - startTime: 17:15
      endTime: 18:00
      title: The DevOps story, from Spar Nord Bank. A glimpse, of the success stories and detours we have experienced, during the past years
      speaker:
      - camillalarsen
      - rasmusroemer
```

Maybe it should be `speakers` which can be one or more. Would that make sense? 

Change this:
```
type Presentation struct {
         ........
	Speaker   *Speaker `json:"speaker"`
}
```
to:
```
type Presentation struct {
         ........
	Speakers   []*Speaker `json:"speakers"`
}
```
