### ISSUE TITLE
Suggestion: Move auto generated files into a folder

### ISSUE THREAD

**Issue by Steiniche** [cloud-native-nordics/meetups#79]
While helping the Aalborg meetup group setup in this repo we talked about that it could create more clarity to move all auto generated in to a folder called "generated" or similar to indicate that these files should not be changed manually.
This would make it more clear that to setup a meetup group or add meetups should be done using meetup.yaml, companies.yaml, and speakers.yaml.

I had to go read the go code again to remember which files to edit and which not to.

**Comment by luxas** [comment]
Yes, I've thought about this and it'd indeed be better. The problem is finding a good interface to use when adding presentations.

When I started thinking about it now; we actually could do something like this:

```
speakers.yaml
companies.yaml
<city>/
   meetup.yaml
generated/
   config.json
   <city>.yaml
   speakers.yaml
```

`meetup.yaml`

```yaml
cfp: https://bit.ly/k8sfin-cfp
# city: Tampere
# country: finland
meetupID: Kubernetes-Tampere
organizers:
- luxas
- netumoliver
- jnummelin
- hoisko
meetups:
  20190102:
     presentations:
     - duration: 10m0s
       slides: https://speakerdeck.com/luxas/kubernetes-and-cncf-meetup-tampere-june-2019
       title: Arrive to the venue, sit down and network with others ;)
     - duration: 5m0s
       title: Introductionary words from the venue sponsor for this time futurice
     recording: https://youtu.be/rnpMBRe0CY0
     sponsors:
       other:
       - luxaslabs
       - cncf
       venue: futurice
```

The key here is to have some easy way to match a single meetup from the `meetup.yaml` file, with a meetup with a real ID and more info received from meetup.com. What I now realized could be a good idea would be to encode `meetups` as a `map[string]Meetup` in the Go code, and match the autogenerated content with the human-generated one based on the date encoded as `YYYYMMDD` (if we can count on no one having two meetups at the same date :joy:)

@kaspernissen @Solisol @netumoliver what do you think?
